### ISSUE TITLE
Implement theme selector

### ISSUE THREAD

**Issue by beefsack** [Miniand/brdg.me-issues#48]
Having custom themes would be cool.  I'm currently using a hack for a dark theme, but it might work something like (completely untested):

``` html
<label><input type="checkbox" onchange="toggleDarkTheme($(this).is(':checked'));" id="themeToggle" /> dark theme</label>
```

``` javascript
function toggleDarkTheme(on) {
    $('#themeToggle').prop('checked', on);
    $(body).toggleClass('theme-dark', on);
    if (on) {
        localStorage.setItem('theme', 'dark');
    } else {
        localStorage.removeItem('theme');
    }
}
$(document).ready(function() {
    if (localStorage.getItem('theme') === 'dark') {
        toggleDarkTheme(true);
    }
});
```

``` css
body.theme-dark {
    color: white;
    background-color: #1d1f21;
}
body.theme-dark div.pure-menu.pure-menu-open {
    background-color: #1d1f21;
}
body.theme-dark #command {
    background-color: #1d1f21;
}
body.theme-dark [style="color:rgb(0,0,0);"] {
    color: white;
}
```
